# Generated by Django 5.0.3 on 2024-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('image', models.ImageField(upload_to='sign_image/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'тип знака',
                'verbose_name_plural': 'типы знаков',
            },
        ),
    ]
